### ISSUE TITLE
FR: Red should be non-compliant

### ISSUE THREAD

**Issue by patgmac** [tuxudo/macos_security_compliance#1]
Love this new plugin.  Suggestion: When something is 100% compliant, or has 0 failures, a color other than red should be used. 

I think most of us associate red with failure, not passing.

**Comment by tuxudo** [comment]
What view are you seeing 100% compliant with red?

**Comment by patgmac** [comment]
Listings > Security Compliance. 

When something is 100% under the "Compliance" column, it's red. 
Or when there are 0 failures under the "Failures" column, it's red. 

![image](https://github.com/tuxudo/macos_security_compliance/assets/614564/e7b375c8-9088-4d62-acb3-d55b8573bc62)

**Comment by patgmac** [comment]
Well, all numbers under Failures are red, which I suppose is fine. But showing 100% compliant in red is my main compliant.

**Comment by tuxudo** [comment]
Thank you for bring this up, the `100.0%` red compliance is now green. The logic used wasn't checking for `100.0`, but instead for `100`. Resolved in v1.1 of the module
